import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Montserrat } from 'next/font/google'


const montserrat = Montserrat({
  weight:["100","300","400","500","600","700","800"],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body className="">
        <NavBar/>
        <div className="container mx-auto justify-center align-middle">
          {children}
        </div>
      </body>
    </html>
  );
}
